version: '3.9'
networks:
  local:
    name: local
services:
  react-ui:
    restart: unless-stopped
    build: 
      context: ../ui.react
      target: dev
      dockerfile: Dockerfile.dev
    image: ui-react-dev
    ports: 
      - 3100:3100
    volumes:
      - ../ui.react:/usr/src/app    
      - /usr/src/app/node_modules
    env_file:
      - envs/ui.env
    networks:
      - local
    depends_on:
      - bff
  bff:  
    restart: unless-stopped
    build:
      context: ../bff/src/simple-budget.bff
      target: dev
      dockerfile: Dockerfile.dev
    image: bff-dev
    ports:
      - 3101:5290
    volumes:
      - ../bff/src/simple-budget.bff:/app/src
    env_file:
      - envs/api.env
    networks:
      - local
    depends_on:
      - identity
      - api
  api: 
    restart: unless-stopped
    image: api-dev:0.0.1
    ports:
      - 3102:5036
    volumes:
      - ../api/src/simple-budget.api:/app/src
      - ./certs/https:/https
      - ./certs/ca:/usr/local/share/ca-certificates
      - /app/src/bin
      - /app/src/obj
    env_file:
      - envs/api.env      
    networks:
      - local
    depends_on:
      identity:
        condition: service_healthy
  identity: 
    restart: unless-stopped
    image: identity-dev:0.0.3
    stdin_open: true
    tty: true
    ports:
      - 3103:5001
    volumes:
      - ../identity/src/asg.identity:/app/src
      - ./certs/https:/https
      - ./certs/ca:/usr/local/share/ca-certificates
      - /app/src/bin
      - /app/src/obj
    env_file:
      - envs/identity.env
    networks:
      - local
    depends_on:    
      db:
        condition: service_healthy      
  seq:
    restart: unless-stopped
    image: datalust/seq
    volumes:
      - ./certs/https:/https
      - ./certs/ca:/usr/local/share/ca-certificates
      - ./seq:/seqinit
    env_file:
      - envs/seq.env
    ports:
      - 3104:443
      - 3107:45341
    networks:
      - local    
  db:
    restart: unless-stopped
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 3106:1433
    env_file:
      - envs/mssql.env
    container_name: sqldb
    hostname: sqldb    
    networks:
      - local
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$${MSSQL_SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s  