version: '3.9'
networks:
  local:
    name: local
services:
  # react-ui:
  #   restart: unless-stopped
  #   build: 
  #     context: ../ui.react
  #     target: dev
  #     dockerfile: Dockerfile.dev
  #   image: ui-react-dev
  #   ports: 
  #     - 3100:3100
  #   volumes:
  #     - ../ui.react:/usr/src/app    
  #     - /usr/src/app/node_modules
  #   env_file:
  #     - envs/ui.env
  #   networks:
  #     - local
  #   depends_on:
  #     bff:
  #       condition: service_healthy
  #   healthcheck:
  #     test: curl --fail https://localhost:5001/health || exit 1
  #     interval: 10s
  #     timeout: 3s
  #     retries: 10
  #     start_period: 10s  
  bff:  
    restart: unless-stopped
    image: simplebudget/bff:0.0.18
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    ports:
      - 3101:5290
    volumes:
      - ../bff/src/simple-budget.bff:/app/src/simple-budget.bff
      - ./certs/https:/https
      - ./certs/ca:/usr/local/share/ca-certificates
      - /app/src/bin
      - /app/src/obj
      - ../packages:/app/packages
    env_file:
      - envs/bff.env
    networks:
      - local
    depends_on:
      identity:
        condition: service_healthy
      api:
        condition: service_healthy   
      seq:
        condition: service_started
    healthcheck:
      test: curl --fail https://localhost:5290/health || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s  
  api: 
    restart: unless-stopped
    image: simplebudget/api:0.0.18
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    ports:
      - 3102:5036
    volumes:
      - ../api/src/simple-budget.api:/app/src/simple-budget.api
      - ./certs/https:/https
      - ./certs/ca:/usr/local/share/ca-certificates
      - /app/src/bin
      - /app/src/obj
      - ../packages:/app/packages
    env_file:
      - envs/api.env      
    networks:
      - local
    depends_on:
      identity:
        condition: service_healthy
      apidb:
        condition: service_healthy   
      seq:
        condition: service_started
    healthcheck:
      test: curl --fail https://localhost:5036/health || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s 
  identity: 
    restart: unless-stopped
    image: simplebudget/identity:0.0.18
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    ports:
      - 3103:5001
    volumes:
      - ../identity/src/asg.identity:/app/src/asg.identity
      - ../identity/src/asg.identity.data:/app/src/asg.identity.data
      - /app/src/asg.identity/bin
      - /app/src/asg.identity/obj
      - /app/src/asg.identity.data/bin
      - /app/src/asg.identity.data/obj
      - ../packages:/app/packages
    env_file:
      - envs/identity.env
    networks:
      - local
    healthcheck:
      test: curl --fail https://localhost:5001/health || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s  
    depends_on:    
      identitydb:
        condition: service_healthy      
      seq:
        condition: service_started
      identitydbmigrator:
        condition: service_completed_successfully 
  identitydbmigrator-watch:    
    image: simplebudget/identity/dbmigrator:watch-0.0.18
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    env_file:
      - envs/identitydbmigrator.env
    networks:
      - local
    volumes:
      - ../identity/src/asg.identity.data.migrator/:/app/src/asg.identity.data.migrator
      - ../identity/src/asg.identity.data:/app/src/asg.identity.data
      - /app/src/asg.identity.data.migrator/bin
      - /app/src/asg.identity.data.migrator/obj
      - /app/src/asg.identity.data/bin
      - /app/src/asg.identity.data/obj
      - ../packages:/app/packages
    depends_on:
      identitydbmigrator:
        condition: service_completed_successfully 
  identitydbmigrator:    
    image: simplebudget/identity/dbmigrator:migrate-0.0.18
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    env_file:
      - envs/identitydbmigrator.env
    networks:
      - local
    volumes:
      - ../identity/src/asg.identity.data.migrator/:/app/src/asg.identity.data.migrator
      - ../identity/src/asg.identity.data:/app/src/asg.identity.data
      - /app/src/asg.identity.data.migrator/bin
      - /app/src/asg.identity.data.migrator/obj
      - /app/src/asg.identity.data/bin
      - /app/src/asg.identity.data/obj
      - ../packages:/app/packages
    depends_on:
      identitydb:
        condition: service_healthy  
      seq:
        condition: service_started
  identitydb:
    restart: unless-stopped
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 3106:1433
    volumes:
    - ../data/identitydb/data:/var/opt/mssql/data
    env_file:
      - envs/mssql.env
    container_name: sqldb-identity
    hostname: sqldb-identity
    networks:
      - local
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$${MSSQL_SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s  
  apidb:
    restart: unless-stopped
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 3107:1433
    volumes:
    - ../data/apidb/data:/var/opt/mssql/data
    env_file:
      - envs/mssql.env
    container_name: sqldb-api
    hostname: sqldb-api
    networks:
      - local
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$${MSSQL_SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s       
  seq:
    restart: unless-stopped
    image: datalust/seq
    volumes:
      - ./certs/https:/https
      - ./certs/ca:/usr/local/share/ca-certificates
      - ./seq:/seqinit
      - ../data/seq:/data
    env_file:
      - envs/seq.env
    ports:
      - 3104:443
      - 3105:45341
    networks:
      - local   
