version: '3.9'
services:
  db:
    restart: unless-stopped
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 3106:1433
    env_file:
      - envs/mssql.env
    container_name: sqldb
    hostname: sqldb